/********************************************
* Autogenereted Macros for CAN_EDS Konstruktion
* for BMS
**********************************************/


#ifndef __BMS_H_
#define __BMS_H_

#define BMS_Device_type_Device_type CAN_EDS_SDO(0x1000,0x0,"Device_type_Device_type",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0x00010196,false,0,false,0,true,0,false,0)
#define BMS_Error_register CAN_EDS_SDO(0x1001,0x0,"Error_register",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Identity_object_Largest_supported_subindex CAN_EDS_SDO(0x1018,0x0,"Identity_object_Largest_supported_subindex",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RO,true,4,false,0,false,0,true,0,false,0)
#define BMS_Identity_object_VendorID CAN_EDS_SDO(0x1018,0x1,"Identity_object_VendorID",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0x5F,false,0,false,0,true,0,false,0)
#define BMS_Identity_object_Product_code CAN_EDS_SDO(0x1018,0x2,"Identity_object_Product_code",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0x17,false,0,false,0,true,0,false,0)
#define BMS_Identity_object_Revision_number CAN_EDS_SDO(0x1018,0x3,"Identity_object_Revision_number",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0x00010004,false,0,false,0,true,0,false,0)
#define BMS_Identity_object_Serial_number CAN_EDS_SDO(0x1018,0x4,"Identity_object_Serial_number",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Manufacturer_status_register CAN_EDS_SDO(0x1002,0x0,"Manufacturer_status_register",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Pre_defined_error_field_Number_of_errors CAN_EDS_SDO(0x1003,0x0,"Pre_defined_error_field_Number_of_errors",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0,false,0,false,0,true,0,false,0)
#define BMS_Pre_defined_error_field_Standard_error_field_1 CAN_EDS_SDO(0x1003,0x1,"Pre_defined_error_field_Standard_error_field_1",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Pre_defined_error_field_Standard_error_field_2 CAN_EDS_SDO(0x1003,0x2,"Pre_defined_error_field_Standard_error_field_2",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Pre_defined_error_field_Standard_error_field_3 CAN_EDS_SDO(0x1003,0x3,"Pre_defined_error_field_Standard_error_field_3",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Pre_defined_error_field_Standard_error_field_4 CAN_EDS_SDO(0x1003,0x4,"Pre_defined_error_field_Standard_error_field_4",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Pre_defined_error_field_Standard_error_field_5 CAN_EDS_SDO(0x1003,0x5,"Pre_defined_error_field_Standard_error_field_5",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Pre_defined_error_field_Standard_error_field_6 CAN_EDS_SDO(0x1003,0x6,"Pre_defined_error_field_Standard_error_field_6",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Pre_defined_error_field_Standard_error_field_7 CAN_EDS_SDO(0x1003,0x7,"Pre_defined_error_field_Standard_error_field_7",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Pre_defined_error_field_Standard_error_field_8 CAN_EDS_SDO(0x1003,0x8,"Pre_defined_error_field_Standard_error_field_8",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_COB_ID_SYNC_message CAN_EDS_SDO(0x1005,0x0,"COB_ID_SYNC_message",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x80,false,0,false,0,true,0,false,0)
#define BMS_Device_name CAN_EDS_SDO(0x1008,0x0,"Device_name",CAN_EDS_SDO::DATA_TYPE_VISIBLE_STRING,CAN_EDS_SDO::ACCESS_TYPE_CONST,true,424d5378,false,0,false,0,true,0,false,0)
#define BMS_Hardware_version CAN_EDS_SDO(0x1009,0x0,"Hardware_version",CAN_EDS_SDO::DATA_TYPE_VISIBLE_STRING,CAN_EDS_SDO::ACCESS_TYPE_CONST,true,312e3030,false,0,false,0,true,0,false,0)
#define BMS_Software_version CAN_EDS_SDO(0x100a,0x0,"Software_version",CAN_EDS_SDO::DATA_TYPE_VISIBLE_STRING,CAN_EDS_SDO::ACCESS_TYPE_CONST,true,312e3035,false,0,false,0,true,0,false,0)
#define BMS_Guard_time CAN_EDS_SDO(0x100c,0x0,"Guard_time",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x0000,false,0,false,0,true,0,false,0)
#define BMS_Life_time_factor CAN_EDS_SDO(0x100d,0x0,"Life_time_factor",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x00,false,0,false,0,true,0,false,0)
#define BMS_Store_parameters_Largest_supported_subindex CAN_EDS_SDO(0x1010,0x0,"Store_parameters_Largest_supported_subindex",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RO,true,4,false,0,false,0,true,0,false,0)
#define BMS_Store_parameters_Save_all_parameters CAN_EDS_SDO(0x1010,0x1,"Store_parameters_Save_all_parameters",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0,false,0,false,0,true,0,false,0)
#define BMS_Store_parameters_Save_communication_parameters CAN_EDS_SDO(0x1010,0x2,"Store_parameters_Save_communication_parameters",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0,false,0,false,0,true,0,false,0)
#define BMS_Store_parameters_Save_application_parameters CAN_EDS_SDO(0x1010,0x3,"Store_parameters_Save_application_parameters",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0,false,0,false,0,true,0,false,0)
#define BMS_Store_parameters_Save_manufactory_parameters CAN_EDS_SDO(0x1010,0x4,"Store_parameters_Save_manufactory_parameters",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0,false,0,false,0,true,0,false,0)
#define BMS_Restore_default_parameters_Largest_supported_subindex CAN_EDS_SDO(0x1011,0x0,"Restore_default_parameters_Largest_supported_subindex",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RO,true,4,false,0,false,0,true,0,false,0)
#define BMS_Restore_default_parameters_Restore_all_default_parameters CAN_EDS_SDO(0x1011,0x1,"Restore_default_parameters_Restore_all_default_parameters",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0,false,0,false,0,true,0,false,0)
#define BMS_Restore_default_parameters_Restore_default_communication_parameters CAN_EDS_SDO(0x1011,0x2,"Restore_default_parameters_Restore_default_communication_parameters",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0,false,0,false,0,true,0,false,0)
#define BMS_Restore_default_parameters_Restore_default_application_parameters CAN_EDS_SDO(0x1011,0x3,"Restore_default_parameters_Restore_default_application_parameters",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0,false,0,false,0,true,0,false,0)
#define BMS_Restore_default_parameters_Restore_default_manufactory_parameters CAN_EDS_SDO(0x1011,0x4,"Restore_default_parameters_Restore_default_manufactory_parameters",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0,false,0,false,0,true,0,false,0)
#define BMS_Emergency_COB_ID CAN_EDS_SDO(0x1014,0x0,"Emergency_COB_ID",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x80,false,0,false,0,true,0,false,0)
#define BMS_Consumer_heartbeat_time_Largest_supported_subindex CAN_EDS_SDO(0x1016,0x0,"Consumer_heartbeat_time_Largest_supported_subindex",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RO,true,1,false,0,false,0,true,0,false,0)
#define BMS_Consumer_heartbeat_time_Consumer_heartbeat_time CAN_EDS_SDO(0x1016,0x1,"Consumer_heartbeat_time_Consumer_heartbeat_time",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0,false,0,false,0,true,0,false,0)
#define BMS_Producer_heartbeat_time CAN_EDS_SDO(0x1017,0x0,"Producer_heartbeat_time",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x00,false,0,false,0,true,0,false,0)
#define BMS_Error_behaviour_Largest_supported_subindex CAN_EDS_SDO(0x1029,0x0,"Error_behaviour_Largest_supported_subindex",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RO,true,1,false,0,false,0,true,0,false,0)
#define BMS_Error_behaviour_Communication_error CAN_EDS_SDO(0x1029,0x1,"Error_behaviour_Communication_error",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RW,true,1,false,0,false,0,true,0,false,0)
#define BMS_1st_transmit_PDO_communication_parameter_Largest_supported_subindex CAN_EDS_SDO(0x1800,0x0,"1st_transmit_PDO_communication_parameter_Largest_supported_subindex",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RO,true,5,false,0,false,0,true,0,false,0)
#define BMS_1st_transmit_PDO_communication_parameter_COB_ID_used_by_PDO CAN_EDS_SDO(0x1800,0x1,"1st_transmit_PDO_communication_parameter_COB_ID_used_by_PDO",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x180,false,0,false,0,true,0,false,0)
#define BMS_1st_transmit_PDO_communication_parameter_Transmission_type CAN_EDS_SDO(0x1800,0x2,"1st_transmit_PDO_communication_parameter_Transmission_type",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RW,true,254,false,0,false,0,true,0,false,0)
#define BMS_1st_transmit_PDO_communication_parameter_Event_time CAN_EDS_SDO(0x1800,0x5,"1st_transmit_PDO_communication_parameter_Event_time",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x0000,false,0,false,0,true,0,false,0)
#define BMS_2nd_transmit_PDO_communication_parameter_Largest_supported_subindex CAN_EDS_SDO(0x1801,0x0,"2nd_transmit_PDO_communication_parameter_Largest_supported_subindex",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RO,true,5,false,0,false,0,true,0,false,0)
#define BMS_2nd_transmit_PDO_communication_parameter_COB_ID_used_by_PDO CAN_EDS_SDO(0x1801,0x1,"2nd_transmit_PDO_communication_parameter_COB_ID_used_by_PDO",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x280,false,0,false,0,true,0,false,0)
#define BMS_2nd_transmit_PDO_communication_parameter_Transmission_type CAN_EDS_SDO(0x1801,0x2,"2nd_transmit_PDO_communication_parameter_Transmission_type",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x02,false,0,false,0,true,0,false,0)
#define BMS_2nd_transmit_PDO_communication_parameter_Event_time CAN_EDS_SDO(0x1801,0x5,"2nd_transmit_PDO_communication_parameter_Event_time",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x0000,false,0,false,0,true,0,false,0)
#define BMS_Transmit_PDO1_mapping_Number_of_mapped_application_objects_in_PDO CAN_EDS_SDO(0x1a00,0x0,"Transmit_PDO1_mapping_Number_of_mapped_application_objects_in_PDO",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RO,true,1,false,0,false,0,true,0,false,0)
#define BMS_Transmit_PDO1_mapping_PDO_mapping_for_the_1st_application_object_to_be_mapped CAN_EDS_SDO(0x1a00,0x1,"Transmit_PDO1_mapping_PDO_mapping_for_the_1st_application_object_to_be_mapped",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0x6004,false,0,false,0,true,0,false,0)
#define BMS_Transmit_PDO2_mapping__Number_of_mapped_application_objects_in_PDO CAN_EDS_SDO(0x1a01,0x0,"Transmit_PDO2_mapping__Number_of_mapped_application_objects_in_PDO",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RO,true,1,false,0,false,0,true,0,false,0)
#define BMS_Transmit_PDO2_mapping__PDO_mapping_for_the_2nd_application_object_to_be_mapped CAN_EDS_SDO(0x1a01,0x1,"Transmit_PDO2_mapping__PDO_mapping_for_the_2nd_application_object_to_be_mapped",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0x6004,false,0,false,0,true,0,false,0)
#define BMS_Operating_parameters CAN_EDS_SDO(0x6000,0x0,"Operating_parameters",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x04,false,0,false,0,true,0,false,0)
#define BMS_Measuring_units_per_revolution CAN_EDS_SDO(0x6001,0x0,"Measuring_units_per_revolution",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x00001000,false,0,false,0,true,0,false,0)
#define BMS_Total_measuring_range_in_measuring_units CAN_EDS_SDO(0x6002,0x0,"Total_measuring_range_in_measuring_units",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x00001000,false,0,false,0,true,0,false,0)
#define BMS_Preset_value CAN_EDS_SDO(0x6003,0x0,"Preset_value",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0,false,0,false,0,true,0,false,0)
#define BMS_Position_value CAN_EDS_SDO(0x6004,0x0,"Position_value",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,1,false,0)
#define BMS_Cyclic_timer_for_PDO1_ CAN_EDS_SDO(0x6200,0x0,"Cyclic_timer_for_PDO1_",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x203,false,0,false,0,true,0,false,0)
#define BMS_Operating_status CAN_EDS_SDO(0x6500,0x0,"Operating_status",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0x04,false,0,false,0,true,0,false,0)
#define BMS_Max_measuring_units_per_revolution CAN_EDS_SDO(0x6501,0x0,"Max_measuring_units_per_revolution",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0x00004000,false,0,false,0,true,0,false,0)
#define BMS_Max_measuring_range_in_measuring_units CAN_EDS_SDO(0x6502,0x0,"Max_measuring_range_in_measuring_units",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0x00004000,false,0,false,0,true,0,false,0)
#define BMS_Alarms CAN_EDS_SDO(0x6503,0x0,"Alarms",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Supported_alarms CAN_EDS_SDO(0x6504,0x0,"Supported_alarms",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0x01,false,0,false,0,true,0,false,0)
#define BMS_Warnings CAN_EDS_SDO(0x6505,0x0,"Warnings",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Supported_warnings CAN_EDS_SDO(0x6506,0x0,"Supported_warnings",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0x04,false,0,false,0,true,0,false,0)
#define BMS_Profile_and_software_version CAN_EDS_SDO(0x6507,0x0,"Profile_and_software_version",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0x01050201,false,0,false,0,true,0,false,0)
#define BMS_Operating_time CAN_EDS_SDO(0x6508,0x0,"Operating_time",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Offset_value CAN_EDS_SDO(0x6509,0x0,"Offset_value",CAN_EDS_SDO::DATA_TYPE_INTEGER_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Seriel_number CAN_EDS_SDO(0x650b,0x0,"Seriel_number",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Baud_rate CAN_EDS_SDO(0x2100,0x0,"Baud_rate",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x02,false,0,false,0,true,0,false,0)
#define BMS_NodeId CAN_EDS_SDO(0x2101,0x0,"NodeId",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RW,false,0,false,0,false,0,true,0,false,0)
#define BMS_Versions_control CAN_EDS_SDO(0x2110,0x0,"Versions_control",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x00000008,false,0,false,0,true,0,false,0)
#define BMS_Drive_data_Largest_supported_subindex CAN_EDS_SDO(0x2201,0x0,"Drive_data_Largest_supported_subindex",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RO,true,3,false,0,false,0,true,0,false,0)
#define BMS_Drive_data_Number_of_position_error CAN_EDS_SDO(0x2201,0x1,"Drive_data_Number_of_position_error",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0x00,false,0,false,0,true,0,false,0)
#define BMS_Drive_data_Time_in_seconds CAN_EDS_SDO(0x2201,0x2,"Drive_data_Time_in_seconds",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Drive_data_Watchdog_counter CAN_EDS_SDO(0x2201,0x3,"Drive_data_Watchdog_counter",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_32,CAN_EDS_SDO::ACCESS_TYPE_RO,true,0,false,0,false,0,true,0,false,0)
#define BMS_Customer_EEPROM_Largest_supported_subindex CAN_EDS_SDO(0x2300,0x0,"Customer_EEPROM_Largest_supported_subindex",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RO,true,7,false,0,false,0,true,0,false,0)
#define BMS_Customer_EEPROM_Data0 CAN_EDS_SDO(0x2300,0x1,"Customer_EEPROM_Data0",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x00,false,0,false,0,true,0,false,0)
#define BMS_Customer_EEPROM_Data1 CAN_EDS_SDO(0x2300,0x2,"Customer_EEPROM_Data1",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x00,false,0,false,0,true,0,false,0)
#define BMS_Customer_EEPROM_Data2 CAN_EDS_SDO(0x2300,0x3,"Customer_EEPROM_Data2",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x00,false,0,false,0,true,0,false,0)
#define BMS_Customer_EEPROM_Data3 CAN_EDS_SDO(0x2300,0x4,"Customer_EEPROM_Data3",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x00,false,0,false,0,true,0,false,0)
#define BMS_Customer_EEPROM_Data4 CAN_EDS_SDO(0x2300,0x5,"Customer_EEPROM_Data4",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x00,false,0,false,0,true,0,false,0)
#define BMS_Customer_EEPROM_Data5 CAN_EDS_SDO(0x2300,0x6,"Customer_EEPROM_Data5",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x00,false,0,false,0,true,0,false,0)
#define BMS_Customer_EEPROM_Data6 CAN_EDS_SDO(0x2300,0x7,"Customer_EEPROM_Data6",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_16,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x00,false,0,false,0,true,0,false,0)
#define BMS_PDO1_addition_event_trigger CAN_EDS_SDO(0x2800,0x0,"PDO1_addition_event_trigger",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x00,false,0,false,0,true,0,false,0)
#define BMS_PDO2_addition_event_trigger CAN_EDS_SDO(0x2801,0x0,"PDO2_addition_event_trigger",CAN_EDS_SDO::DATA_TYPE_UNSIGNED_8,CAN_EDS_SDO::ACCESS_TYPE_RW,true,0x00,false,0,false,0,true,0,false,0)

#endif//__BMS_H_
